version: "3"
services:
  rstudio:
    container_name: rstudio
    image: tidyverse:3.6.3_jp
    user: root
    volumes:
      - ../kitematic:/home/rstudio/kitematic
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8787:8787
    environment:
    - DISABLE_AUTH=true
    working_dir: /home/rstudio/kitematic/
    restart: unless-stopped
    tty: true
    privileged: true
    stdin_open: true
    