###1.1時系列データ###
pdf("図1.1 いろいろな時系列の例.pdf")
library(TSSS)

data(HAKUSAN)
data(Sunspot)
data(Temperature)
data(BLSALLFOOD)
data(WHARD)
data(MYE1F)
data(Nikkei225)
data(Rainfall)
data(Haibara)

par(mar=c(2,2,3,1)+0.1)
plot(HAKUSAN[,1], main="(a)")
plot(Sunspot, main="(b)")
plot(Temperature, main="(c)")
plot(BLSALLFOOD, main="(d)")
plot(WHARD, main="(e)")
plot(MYE1F, main="(f)")
plot(Nikkei225, main="(g)")
plot(Haibara, main="(h)")
plot(HAKUSAN[, c(2,3,4)], main="(i)")